language: go

sudo: required

services:
  - mysql
  - postgresql

addons:
  postgresql: 9.5

go:
    - tip

install:
    - go get -v github.com/lib/pq
    - go get -v github.com/go-sql-driver/mysql
    - go get -v github.com/mattn/go-sqlite3
    - go get -t -v ./...

script:
    - go test -v -covermode=count -coverprofile=coverage.out
    - go test -v -covermode=count -coverprofile=sqlite.out ./dialects/sqlite
    - go test -v -covermode=count -coverprofile=postgres.out ./dialects/postgres
    - go test -v -covermode=count -coverprofile=mysql.out ./dialects/mysql
    - tail --lines +2 sqlite.out >> coverage.out
    - tail --lines +2 postgres.out >> coverage.out
    - tail --lines +2 mysql.out >> coverage.out
    - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken 0yIEy3NVX2lXn3KxYzHjkla7EWGjvmLAp

before_script:
  - mysql -e 'create database IF NOT EXISTS qb_test;'
  - psql -U postgres -c 'CREATE DATABASE qb_test;'
